#!/bin/bash
LOCKFILE_UPDATE=update.lock
LOCKFILE_EXPORT=export.lock

trap "rmdir $LOCKFILE_EXPORT; exit 1;" SIGINT SIGTERM
if mkdir "$LOCKFILE_EXPORT"; then
	echo "locking suceeded" >&2
	
	while [ -d "$LOCKFILE_UPDATE" ***REMOVED*** do
		echo "Update Lock active. Retry in 10s...";
		sleep 10;
	done;
	
	echo "Starting the export.";
	php artisan fairmondobooks:export;
	rmdir $LOCKFILE_EXPORT;
else
	echo "locking failed - exit"
	exit 1
fi
