#!/bin/bash
LOCKFILE_UPDATE=update.lock
LOCKFILE_EXPORT=export.lock

function repeatUntilCleanExit {
	EXITCODE=1
	while [ $EXITCODE -ne 0 ***REMOVED*** do
		if [ -d "$LOCKFILE_EXPORT" ***REMOVED*** then
			echo "update lock active";
			removeLockfile;
			exit 0;
		else
			$@;
			EXITCODE=$?;
		fi;
	done;
}

function removeLockfile {
	rmdir "$LOCKFILE_UPDATE";
}

trap "removeLockfile; exit 1;" SIGINT SIGTERM

if mkdir "$LOCKFILE_UPDATE"; then
        echo "locking suceeded" >&2

        # import catalog updates
        repeatUntilCleanExit php artisan pull --reverse;

        # import annotations
        repeatUntilCleanExit php artisan pull:annotations;

        # remove lockfile
        removeLockfile;
        exit 0;
else
        echo "locking failed - exit"
        exit 1
fi

