#!/bin/bash
LOCKFILE_UPDATE=update.lock
LOCKFILE_EXPORT=export.lock
date "+[%Y-%m-%d %H:%M:%S]"

# exit code 0 means there are no more files to download
# exit code 1 means there was an error
# exit code 2 means there are more files to download
function repeatUntilCleanExit {
	EXITCODE=2
	while [ $EXITCODE -eq 2 ]; do
		if [ -d "$LOCKFILE_EXPORT" ]; then
			echo "export lock active";
			removeLockfile;
			exit 0;
		else
			$@;
			EXITCODE=$?;
		fi;
	done;
}

function removeLockfile {
	rmdir "$LOCKFILE_UPDATE";
}

trap "removeLockfile; exit 1;" SIGINT SIGTERM

if [ ! -d "$LOCKFILE_EXPORT" ] && mkdir "$LOCKFILE_UPDATE"; then
	echo "locking suceeded" >&2

        # import catalog updates
        repeatUntilCleanExit php artisan pull -vv;

        # import annotations
        repeatUntilCleanExit php artisan pull:annotations -vv;

        # remove lockfile
        removeLockfile;
        exit 0;
else
        echo "locking failed - exit"
        exit 1
fi

